import { context } from 'esbuild';

const production = process.argv[2] === 'production';
const buildContext = await context({
  banner: {
    js: '/* Generated by esbuild. Source: https://github.com/Mahjong404/LoomTable-Obsidian-Plugin */',
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', 'electron'],
  format: 'cjs',
  logLevel: 'info',
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  sourcemap: production ? false : 'inline',
  target: 'es2022',
  treeShaking: true,
});

if (production) {
  await buildContext.rebuild();
  await buildContext.dispose();
} else {
  await buildContext.watch();
}
